### ISSUE TITLE
Altitude information

### ISSUE THREAD

**Issue by certifiedloud** [amilich/VFR-Flight-Planner#2]
Is this app altitude aware? I planned a route (KSGU -> KPVU) and it would have me plow right through a mountain. Of course it's the pilots responsibility to select an appropriate altitude, but it would be nice if the app said something like "That altitude is dangerous", and "This altitude is not appropriate for the chosen direction of flight".

**Comment by amilich** [comment]
I'm working on checking the altitude at intervals during the trip and, if it (or the direction of flight) conflicts with the user's given altitude, the app will suggest a new cruising altitude. This feature isn't yet implemented but I'm working on it now.

**Comment by amilich** [comment]
Just fixed it and added elevation map to flight plan page.
